#!/bin/bash

# Check for dry run status
if [ "$1" = '--dry-run' ]; then
	dry_state='--dry-run'
else
	dry_state=''
fi

# Run
rsync -rltpxh ${dry_state} --progress --exclude '.DS_Store' --exclude '.localized' --exclude '._*' --exclude '@eaDir/' --files-from="$HOME/etc/backup-to-nas/include.list" --exclude-from="$HOME/etc/backup-to-nas/exclude.list" --delete $HOME Fabien@diskstation.home:/volume1/Fabien_Perso/$USER

# Close
exit 0
