#!/usr/bin/env bash

mdutil -a -i off
launchctl unload -w /System/Library/LaunchDaemons/com.apple.metadata.mds.plist
chmod 0600 /System/Library/CoreServices/Search.bundle/Contents/MacOS/Search
killall SystemUIServer
