#!/usr/bin/env bash

# Check arguments
if [[ $# != 1 || ! $1 || ! -d $1 || ! -r $1 ]]; then
  echo 'You must specify a valid (existing and readable) directory path as single argument.'
  exit 1
fi

# Run
find $1 -type f ! -path '*/.git/*' ! -name .DS_Store ! -perm 0644 -exec ls -lph {} \;
find $1 -type d ! -path '*/.git/*' ! -name .DS_Store ! -perm 0755 -exec ls -lphd {} \;
