#!/usr/bin/env bash

# Validate target path
if [[ ! $1 || ! -d $1 || ! -r $1 ]]; then
  echo 'You must specify a valid directory path as argument.'
  exit 1
fi

# Run
find $1 -type f ! -path '*/.git/*' ! -name .DS_Store ! -perm 0644 -exec ls -lph {} \;
find $1 -type d ! -path '*/.git/*' ! -name .DS_Store ! -perm 0755 -exec ls -lphd {} \;
